name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v2
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: build
      run : msbuild.exe -property:Configuration=Release
    - name: test
      run: tree /F
    - uses: actions/upload-artifact@v2
      with:
        name: SemaphoreHelper.exe
        path: ${{ github.workspace }}/x64/Release/SemaphoreHelper.exe
